---
- name: httpd deploy
  hosts: all
  tasks:
  - name: httpd install
    yum:
      name: httpd
      state: latest

  - name: httpd start/enable
    systemd:
      state: started
      name: httpd
      enabled: yes
